//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityPlusInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityPlusInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream activated {
            get {
                return ResourceManager.GetStream("activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream active_shooter_ulsa {
            get {
                return ResourceManager.GetStream("active_shooter_ulsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Agencies&gt;
        ///	&lt;Agency&gt;
        ///		&lt;Name&gt;Gruppe Sechs Security&lt;/Name&gt;
        ///		&lt;ShortName&gt;GRU&lt;/ShortName&gt;
        ///		&lt;ScriptName&gt;gru&lt;/ScriptName&gt;
        ///		&lt;TextureDictionary&gt;dia_police&lt;/TextureDictionary&gt;
        ///		&lt;TextureName&gt;dia_police&lt;/TextureName&gt;
        ///		&lt;Inventory&gt;patrol&lt;/Inventory&gt;
        ///		&lt;Loadout&gt;
        ///			&lt;Name&gt;Response Unit&lt;/Name&gt;
        ///			&lt;Vehicles&gt;
        ///				&lt;Vehicle&gt;cvpi&lt;/Vehicle&gt;
        ///				&lt;Vehicle&gt;charger&lt;/Vehicle&gt;
        ///			&lt;/Vehicles&gt;
        ///			&lt;Peds&gt;
        ///				&lt;!-- 100% chance of male peds --&gt;
        ///				&lt;Ped inventory=&quot;grupatrol&quot;&gt;s_m_m_security_01&lt;/Ped&gt; 
        ///			&lt;/Peds&gt;
        ///			&lt;Num [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string agency_gru {
            get {
                return ResourceManager.GetString("agency_gru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream any_avail_armoured_security_officer {
            get {
                return ResourceManager.GetStream("any_avail_armoured_security_officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream any_avail_security_officer {
            get {
                return ResourceManager.GetStream("any_avail_security_officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream armoured_car_escort {
            get {
                return ResourceManager.GetStream("armoured_car_escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream armoured_car_money_transfer {
            get {
                return ResourceManager.GetStream("armoured_car_money_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- ELS VEHICLE CONFIGURATION FILE --&gt;
        ///&lt;vcfroot Description=&quot;Gruppe Sechs Armoured Car&quot; Author=&quot;ObsidianGames/SneakySteve&quot; &gt;
        ///	&lt;!-- INTERFACE --&gt;
        ///	&lt;INTERFACE&gt;
        ///		&lt;LstgActivationType&gt;manual&lt;/LstgActivationType&gt;
        ///		&lt;DefaultSirenMode&gt;standby&lt;/DefaultSirenMode&gt;
        ///		&lt;InfoPanelHeaderColor&gt;grey&lt;/InfoPanelHeaderColor&gt;
        ///		&lt;InfoPanelButtonLightColor&gt;red&lt;/InfoPanelButtonLightColor&gt;
        ///	&lt;/INTERFACE&gt;
        ///	&lt;!-- EXTRAS OVERRIDE AND ENV LIGHTING--&gt;
        ///	&lt;EOVERRIDE&gt;
        ///		&lt;Extra01 IsElsControl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string armouredcar {
            get {
                return ResourceManager.GetString("armouredcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream attention_avail_armoured_security {
            get {
                return ResourceManager.GetStream("attention_avail_armoured_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream attention_avail_security {
            get {
                return ResourceManager.GetStream("attention_avail_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream casing_robbery {
            get {
                return ResourceManager.GetStream("casing_robbery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- ELS VEHICLE CONFIGURATION FILE --&gt;
        ///&lt;vcfroot Description=&quot;Gruppe Sechs Charger&quot; Author=&quot;Luxart/SneakySteve&quot; &gt;
        ///	&lt;!-- INTERFACE --&gt;
        ///	&lt;INTERFACE&gt;
        ///		&lt;LstgActivationType&gt;manual&lt;/LstgActivationType&gt;
        ///		&lt;DefaultSirenMode&gt;standby&lt;/DefaultSirenMode&gt;
        ///		&lt;InfoPanelHeaderColor&gt;grey&lt;/InfoPanelHeaderColor&gt;
        ///		&lt;InfoPanelButtonLightColor&gt;orange&lt;/InfoPanelButtonLightColor&gt;
        ///	&lt;/INTERFACE&gt;
        ///	&lt;!-- EXTRAS OVERRIDE AND ENV LIGHTING--&gt;
        ///	&lt;EOVERRIDE&gt;	
        ///		&lt;Extra01 IsElsControlled=&quot;tru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string charger {
            get {
                return ResourceManager.GetString("charger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream code_adam {
            get {
                return ResourceManager.GetStream("code_adam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream consumer_refusing_to_pay {
            get {
                return ResourceManager.GetStream("consumer_refusing_to_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- ELS VEHICLE CONFIGURATION FILE --&gt;
        ///&lt;vcfroot Description=&quot;Gruppe Sechs CVPI&quot; Author=&quot;Luxart/SneakySteve&quot; &gt;
        ///	&lt;!-- INTERFACE --&gt;
        ///	&lt;INTERFACE&gt;
        ///		&lt;LstgActivationType&gt;manual&lt;/LstgActivationType&gt;
        ///		&lt;DefaultSirenMode&gt;standby&lt;/DefaultSirenMode&gt;
        ///		&lt;InfoPanelHeaderColor&gt;grey&lt;/InfoPanelHeaderColor&gt;
        ///		&lt;InfoPanelButtonLightColor&gt;purple&lt;/InfoPanelButtonLightColor&gt;
        ///	&lt;/INTERFACE&gt;
        ///	&lt;!-- EXTRAS OVERRIDE AND ENV LIGHTING--&gt;
        ///	&lt;EOVERRIDE&gt;	
        ///		&lt;Extra01 IsElsControlled=&quot;true&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cvpi {
            get {
                return ResourceManager.GetString("cvpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Duty&gt;
        ///    &lt;Peds&gt;
        ///        &lt;Agency&gt;gru&lt;/Agency&gt;
        ///    &lt;/Peds&gt;
        ///    &lt;Vehicles&gt;
        ///        &lt;Agency&gt;gru&lt;/Agency&gt;
        ///    &lt;/Vehicles&gt;
        ///    &lt;VehicleDescriptions&gt;
        ///        &lt;Description name=&quot;CVPI&quot; fullName=&quot;Ford Crown Victoria&quot; agencyRef=&quot;gru&quot;&gt;cvpi&lt;/Description&gt;
        ///        &lt;Description name=&quot;Charger&quot; fullName=&quot;Dodge Charger&quot; agencyRef=&quot;gru&quot;&gt;charger&lt;/Description&gt;
        ///        &lt;Description name=&quot;FPIU&quot; fullName=&quot;Ford Explorer&quot; agencyRef=&quot;gru&quot;&gt;fpiu&lt;/Description&gt;
        ///        &lt;Description name=&quot;Armoured Car&quot; fullName=&quot;PSNI Pangolin&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string duty_selection_gru {
            get {
                return ResourceManager.GetString("duty_selection_gru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Agencies&gt;
        ///	&lt;Agency&gt;
        ///		&lt;Name&gt;Gruppe Sechs Security&lt;/Name&gt;
        ///		&lt;ShortName&gt;GRU&lt;/ShortName&gt;
        ///		&lt;ScriptName&gt;gru&lt;/ScriptName&gt;
        ///		&lt;TextureDictionary&gt;dia_police&lt;/TextureDictionary&gt;
        ///		&lt;TextureName&gt;dia_police&lt;/TextureName&gt;
        ///		&lt;Inventory&gt;patrol&lt;/Inventory&gt;
        ///		&lt;Loadout chance=&quot;50&quot;&gt;
        ///			&lt;Name&gt;Response Unit&lt;/Name&gt;
        ///			&lt;Vehicles&gt;
        ///				&lt;Vehicle&gt;cvpi&lt;/Vehicle&gt;
        ///				&lt;Vehicle&gt;charger&lt;/Vehicle&gt;
        ///			&lt;/Vehicles&gt;
        ///			&lt;Peds&gt;
        ///				&lt;!-- 50% chance of male peds --&gt;
        ///					&lt;!-- 1/3 of a chance outfit A --&gt;
        ///					&lt;Ped chance=&quot;16&quot; out [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eup_agency_gru {
            get {
                return ResourceManager.GetString("eup_agency_gru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Duty&gt;
        ///    &lt;Peds&gt;
        ///        &lt;Agency&gt;gru&lt;/Agency&gt;
        ///    &lt;/Peds&gt;
        ///    &lt;Vehicles&gt;
        ///        &lt;Agency&gt;gru&lt;/Agency&gt;
        ///    &lt;/Vehicles&gt;
        ///    &lt;VehicleDescriptions&gt;
        ///        &lt;Description name=&quot;CVPI&quot; fullName=&quot;Ford Crown Victoria&quot; agencyRef=&quot;gru&quot;&gt;cvpi&lt;/Description&gt;
        ///        &lt;Description name=&quot;Charger&quot; fullName=&quot;Dodge Charger&quot; agencyRef=&quot;gru&quot;&gt;charger&lt;/Description&gt;
        ///        &lt;Description name=&quot;FPIU&quot; fullName=&quot;Ford Explorer&quot; agencyRef=&quot;gru&quot;&gt;fpiu&lt;/Description&gt;
        ///        &lt;Description name=&quot;Armoured Car&quot; fullName=&quot;Lenco Bearcat&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eup_duty_selection_gru {
            get {
                return ResourceManager.GetString("eup_duty_selection_gru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Inventories&gt;
        ///	&lt;Inventory&gt;
        ///        &lt;Name&gt;GRU Response&lt;/Name&gt;
        ///        &lt;ScriptName&gt;grupatrol&lt;/ScriptName&gt;
        ///        &lt;Weapon chance=&quot;10&quot;&gt;
        ///            &lt;Model&gt;WEAPON_PUMPSHOTGUN&lt;/Model&gt;
        ///            &lt;Component&gt;COMPONENT_AT_AR_FLSH&lt;/Component&gt; &lt;!-- Flashlight --&gt;
        ///        &lt;/Weapon&gt;
        ///        &lt;Weapon chance=&quot;100&quot;&gt;
        ///            &lt;Model&gt;WEAPON_PISTOL&lt;/Model&gt;
        ///            &lt;Component&gt;COMPONENT_AT_PI_FLSH&lt;/Component&gt; &lt;!-- Flashlight --&gt;
        ///        &lt;/Weapon&gt;
        ///        &lt;StunWeapon&gt;WEAPON_STUNGUN&lt;/StunWeapon&gt;
        ///        &lt;Armo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eup_inventory_gru {
            get {
                return ResourceManager.GetString("eup_inventory_gru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Outfits&gt;
        ///	&lt;Outfit&gt;
        ///		&lt;Name&gt;Security Officer A&lt;/Name&gt;
        ///		&lt;ScriptName&gt;gru_class_a&lt;/ScriptName&gt;
        ///		&lt;Variations&gt;
        ///			&lt;Variation&gt;
        ///				&lt;Name&gt;Officer&lt;/Name&gt;
        ///				&lt;ScriptName&gt;gru_m_base&lt;/ScriptName&gt;
        ///				&lt;Gender&gt;male&lt;/Gender&gt;
        ///				  &lt;Components&gt;
        ///				    &lt;Component id=&quot;2&quot; drawable=&quot;55&quot; texture=&quot;0&quot; /&gt;
        ///					&lt;Component id=&quot;3&quot; drawable=&quot;4&quot; texture=&quot;0&quot; /&gt;
        ///					&lt;Component id=&quot;4&quot; drawable=&quot;25&quot; texture=&quot;5&quot; /&gt;
        ///					&lt;Component id=&quot;5&quot; drawable=&quot;39&quot; texture=&quot;0&quot; /&gt;
        ///					&lt;Component id=&quot;6&quot; drawable=&quot;51&quot; texture=&quot;0&quot; /&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eup_outfits_gru {
            get {
                return ResourceManager.GetString("eup_outfits_gru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///  This file contains additional Special Units that will be added into the bottom of Ultimate Backup Menu (orange color)
        ///
        ///  Improtant notes:
        ///
        ///    # You may have as many as &quot;SpecialUnit&quot; tags as you want.
        ///
        ///    # The &quot;SpecialUnit&quot; children nodes can consist of the mix from default regions (e.g. LocalPatrol, etc.) and custom regions (which requires &quot;Zones&quot;). Please refer to the existing examples
        ///
        ///    # The &quot;SpecialUnit&quot; tag has the following attributes:
        ///      - &quot;name&quot; is the name of the special u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eup_SpecialUnits {
            get {
                return ResourceManager.GetString("eup_SpecialUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PoliceStations&gt;
        ///	&lt;Station&gt;
        ///		&lt;Name&gt;Gruppe Sechs Corporate Office&lt;/Name&gt;
        ///		&lt;Agency&gt;gru&lt;/Agency&gt;
        ///		&lt;ScriptName&gt;gruoffice&lt;/ScriptName&gt;
        ///		&lt;Position&gt;-196.9496f, -831.0863f, 30.75992f&lt;/Position&gt;
        ///		&lt;Heading&gt;116.3795f&lt;/Heading&gt;
        ///		&lt;DropOffPosition&gt;-194.079f, -832.2991f, 30.78524f&lt;/DropOffPosition&gt;
        ///		&lt;GaragePosition&gt;-195.3494f, -835.0737f, 30.73014f; 119.0082f&lt;/GaragePosition&gt;
        ///		&lt;GarageSpawnPosition&gt;-178.4412f, -832.4777f, 30.15549f; 160.966f&lt;/GarageSpawnPosition&gt;
        ///	&lt;/Station&gt;
        ///&lt;/PoliceStations&gt;.
        /// </summary>
        internal static string eup_stations_gru {
            get {
                return ResourceManager.GetString("eup_stations_gru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream fake_credentials {
            get {
                return ResourceManager.GetStream("fake_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- ELS VEHICLE CONFIGURATION FILE --&gt;
        ///&lt;vcfroot Description=&quot;Gruppe Sechs FPIU&quot; Author=&quot;Luxart/SneakySteve&quot; &gt;
        ///	&lt;!-- INTERFACE --&gt;
        ///	&lt;INTERFACE&gt;
        ///		&lt;LstgActivationType&gt;manual&lt;/LstgActivationType&gt;
        ///		&lt;DefaultSirenMode&gt;standby&lt;/DefaultSirenMode&gt;
        ///		&lt;InfoPanelHeaderColor&gt;grey&lt;/InfoPanelHeaderColor&gt;
        ///		&lt;InfoPanelButtonLightColor&gt;orange&lt;/InfoPanelButtonLightColor&gt;
        ///	&lt;/INTERFACE&gt;
        ///	&lt;!-- EXTRAS OVERRIDE AND ENV LIGHTING--&gt;
        ///	&lt;EOVERRIDE&gt;	
        ///		&lt;Extra01 IsElsControlled=&quot;true&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fpiu {
            get {
                return ResourceManager.GetString("fpiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream guard_duty {
            get {
                return ResourceManager.GetStream("guard_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HeapAdjuster {
            get {
                object obj = ResourceManager.GetObject("HeapAdjuster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HEAP_SETTINGS]
        ///HEAP_SIZE = 750.
        /// </summary>
        internal static string HeapConfig {
            get {
                return ResourceManager.GetString("HeapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream insurgency_sandy_air {
            get {
                return ResourceManager.GetStream("insurgency_sandy_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Inventories&gt;
        ///	&lt;Inventory&gt;
        ///        &lt;Name&gt;GRU Response&lt;/Name&gt;
        ///        &lt;ScriptName&gt;grupatrol&lt;/ScriptName&gt;
        ///        &lt;Weapon chance=&quot;10&quot;&gt;
        ///            &lt;Model&gt;WEAPON_PUMPSHOTGUN&lt;/Model&gt;
        ///            &lt;Component&gt;COMPONENT_AT_AR_FLSH&lt;/Component&gt; &lt;!-- Flashlight --&gt;
        ///        &lt;/Weapon&gt;
        ///        &lt;Weapon chance=&quot;100&quot;&gt;
        ///            &lt;Model&gt;WEAPON_PISTOL&lt;/Model&gt;
        ///            &lt;Component&gt;COMPONENT_AT_PI_FLSH&lt;/Component&gt; &lt;!-- Flashlight --&gt;
        ///        &lt;/Weapon&gt;
        ///        &lt;StunWeapon&gt;WEAPON_STUNGUN&lt;/StunWeapon&gt;
        ///        &lt;Armo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inventory_gru {
            get {
                return ResourceManager.GetString("inventory_gru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream loitering {
            get {
                return ResourceManager.GetStream("loitering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream open_carry {
            get {
                return ResourceManager.GetStream("open_carry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream private_escort {
            get {
                return ResourceManager.GetStream("private_escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream residence_alarm {
            get {
                return ResourceManager.GetStream("residence_alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RNUI_LICENSE {
            get {
                object obj = ResourceManager.GetObject("RNUI_LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RNUI_NOTICE {
            get {
                object obj = ResourceManager.GetObject("RNUI_NOTICE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RNUI_RAGENativeUIDLL {
            get {
                object obj = ResourceManager.GetObject("RNUI_RAGENativeUIDLL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RNUI_RAGENativeUIPDB {
            get {
                object obj = ResourceManager.GetObject("RNUI_RAGENativeUIPDB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;RAGENativeUI&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;E:RAGENativeUI.BaseCollection`1.ItemAdded&quot;&gt;
        ///            &lt;summary&gt;
        ///            Occurs when an item is added to this &lt;see cref=&quot;T:RAGENativeUI.BaseCollection`1&quot;/&gt; using &lt;see cref=&quot;M:RAGENativeUI.BaseCollection`1.Add(`0)&quot;/&gt;.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;E:RAGENativeUI.BaseCollection`1.ItemRemoved&quot;&gt;
        ///            &lt;summary&gt;
        ///            Occur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RNUI_RAGENativeUIXML {
            get {
                return ResourceManager.GetString("RNUI_RAGENativeUIXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Security_ {
            get {
                object obj = ResourceManager.GetObject("Security_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Identifier]
        ///; This is what the dispatcher will refer to you as.
        ///ID=&quot;Security Car 1&quot;
        ///; This is your Security Officer&apos;s name.
        ///Name=&quot;ChangeMe&quot;
        ///[Keys]
        ///; You can find a list of accepted keys here https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=net-5.0
        ///; This is what you press to activate Security+ once on duty in LSPDFR
        ///Activate=&quot;F2&quot;
        ///; This is what you press to end a call
        ///EndCall=&quot;NumPad7&quot;
        ///[Options]
        ///; This determines whether or not distance checks will be made
        ///; true mean [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecurityConfig {
            get {
                return ResourceManager.GetString("SecurityConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SecurityPlus {
            get {
                object obj = ResourceManager.GetObject("SecurityPlus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Identifier]
        ///; This is what the dispatcher will refer to you as.
        ///ID=&quot;Security Car 1&quot;
        ///; This is your Security Officer&apos;s name.
        ///Name=&quot;ChangeMe&quot;
        ///[Keys]
        ///; You can find a list of accepted keys here https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=net-5.0
        ///; This is what you press to activate Security+ once on duty in LSPDFR
        ///Activate=&quot;F2&quot;
        ///; This is what you press to end a call
        ///EndCall=&quot;NumPad7&quot;
        ///[Options]
        ///; This determines whether you want Security+ to always auto-activate when  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecurityPlus1 {
            get {
                return ResourceManager.GetString("SecurityPlus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///  This file contains additional Special Units that will be added into the bottom of Ultimate Backup Menu (orange color)
        ///
        ///  Improtant notes:
        ///
        ///    # You may have as many as &quot;SpecialUnit&quot; tags as you want.
        ///
        ///    # The &quot;SpecialUnit&quot; children nodes can consist of the mix from default regions (e.g. LocalPatrol, etc.) and custom regions (which requires &quot;Zones&quot;). Please refer to the existing examples
        ///
        ///    # The &quot;SpecialUnit&quot; tag has the following attributes:
        ///      - &quot;name&quot; is the name of the special u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpecialUnits {
            get {
                return ResourceManager.GetString("SpecialUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PoliceStations&gt;
        ///	&lt;Station&gt;
        ///		&lt;Name&gt;Gruppe Sechs Corporate Office&lt;/Name&gt;
        ///		&lt;Agency&gt;gru&lt;/Agency&gt;
        ///		&lt;ScriptName&gt;gruoffice&lt;/ScriptName&gt;
        ///		&lt;Position&gt;-196.9496f, -831.0863f, 30.75992f&lt;/Position&gt;
        ///		&lt;Heading&gt;116.3795f&lt;/Heading&gt;
        ///		&lt;DropOffPosition&gt;-194.079f, -832.2991f, 30.78524f&lt;/DropOffPosition&gt;
        ///		&lt;GaragePosition&gt;-195.3494f, -835.0737f, 30.73014f; 119.0082f&lt;/GaragePosition&gt;
        ///		&lt;GarageSpawnPosition&gt;-178.4412f, -832.4777f, 30.15549f; 160.966f&lt;/GarageSpawnPosition&gt;
        ///	&lt;/Station&gt;
        ///&lt;/PoliceStations&gt;.
        /// </summary>
        internal static string stations_gru {
            get {
                return ResourceManager.GetString("stations_gru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream student_feeling_unsafe {
            get {
                return ResourceManager.GetStream("student_feeling_unsafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream student_in_distress {
            get {
                return ResourceManager.GetStream("student_in_distress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sus_person_bank {
            get {
                return ResourceManager.GetStream("sus_person_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NOOSE]
        ///Gender=Male
        ///Hat=0:0
        ///Glasses=0:0
        ///Ear=0:0
        ///Watch=0:0
        ///Mask=1:1
        ///Top=4:1
        ///UpperSkin=13:1
        ///Decal=1:1
        ///UnderCoat=134:2
        ///Pants=11:5
        ///Shoes=11:1
        ///Accessories=7:1
        ///Armor=44:1
        ///Parachute=1:1
        ///
        ///[Male Officer A]
        ///Gender=Male
        ///Hat=42:1
        ///Glasses=0:0
        ///Ear=0:0
        ///Watch=0:0
        ///Mask=1:1
        ///Top=216:3
        ///UpperSkin=5:1
        ///Decal=1:1
        ///UnderCoat=39:2
        ///Pants=26:6
        ///Shoes=52:1
        ///Accessories=7:1
        ///Armor=14:1
        ///Parachute=40:1
        ///
        ///[Male Officer B]
        ///Gender=Male
        ///Hat=0:0
        ///Glasses=0:0
        ///Ear=0:0
        ///Watch=0:0
        ///Mask=1:1
        ///Top=215:3
        ///UpperSkin=5:1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wardrobe {
            get {
                return ResourceManager.GetString("wardrobe", resourceCulture);
            }
        }
    }
}
